import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="antialiased font-sans bg-gray-200">
        <Navbar />
        <div className="pt-20">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
